### ISSUE TITLE
Sessions not found

### ISSUE THREAD

**Issue by bamal** [courtois-neuromod/cneuromod_docs#14]
Hello ! 

In cneuromod data, movie10, some sessions are skipped in the case of subject 3, session 8 is missing for a total of 12 sessions for this subject. Similarly, subject 5 does not have session 6.

Any idea why this failed @bpinsard ?

**Comment by julieaboyle1** [comment]
Hi Amal, for subject 3, we skipped session 8 in the numbering when scanning, meaning we went straight from session 7 to session 9. Session 8 should in fact be empty (I think). @bpinsard any insight? @bamal  you will notice that subject 3 has 13 sessions instead. 

The same happened, for subject 5, session 6, we skipped from session 5 to session 7 in the naming at the console.

**Comment by pbellec** [comment]
it is a bit weird to skip session numbers, but I think this is not a problem for BIDS, so we will likely leave it like that. @bpinsard what did you decide on this?

**Comment by bpinsard** [comment]
Yes it is weird, but this is neuromod, it may even give it charm. ;) 
I think it is still bids valid (raises warning anyway because participant don't have the same number of session and same series in each session).
The thing is that the session have no important meaning in the current neuromod sub-datasets.
The other option is to rename all the dicoms of all the sessions after the skipped one and rerun the conversion, or rename all the BIDS files.
At some point we want to automate things, but we end up doing a lot of editing. :/

**Comment by pbellec** [comment]
stall issues. I don't know if that was addressed, but if not let's just keep it that way.
